import React from 'react';
import RootLayout, { metadata } from './layout';

describe('RootLayout', () => {
  it('exports metadata', () => {
    expect(metadata.title).toBe('Create Next App');
    expect(metadata.description).toBe('Generated by create next app');
  });

  it('wraps children in html and body elements', () => {
    const element = RootLayout({ children: <div>Child</div> }) as React.ReactElement<{
      children: React.ReactElement;
      lang: string;
    }>;
    const body = element.props.children as React.ReactElement<{
      children: React.ReactElement;
      className: string;
    }>;
    const child = body.props.children as React.ReactElement<{ children: string }>;

    expect(element.type).toBe('html');
    expect(element.props.lang).toBe('en');
    expect(body.type).toBe('body');
    expect(body.props.className).toBe('antialiased');
    expect(child.type).toBe('div');
    expect(child.props.children).toBe('Child');
  });
});
